### ISSUE TITLE
Add Metropolia Myllypuro

### ISSUE THREAD

**Issue by vaahtokarkki** [Kanttiinit/kitchen#14]
Please add menu of Metropolia Myllypuro (Sodexo)

- https://www.sodexo.fi/ravintolat/metropolia-myllypuro

**Comment by maxjvh** [comment]
@vaahtokarkki thanks for the feedback! the Myllypuro restaurant has been added along with a new area "Myllypuro".

**Comment by vaahtokarkki** [comment]
Super! The area could be even East Helsinki, as in Myllypuro is afaik only one student restaurant 😄

**Comment by maxjvh** [comment]
good point! changed the area name.
