### ISSUE TITLE
Add Ravintola Luova

### ISSUE THREAD

**Issue by otahontas** [Kanttiinit/kitchen#16]
Ravintola Luova offers student lunches at Metropolia Arabia Campus, here's the lunch list in Finnish:
http://www.compass-group.fi/Ravintolat/Helsinki/Ravintola-Luova/Lounaslista/

Do you take PR's for new parsers? I'd like to contribute, if it's ok to you :smile:

**Comment by maxjvh** [comment]
hey @otahontas! thanks for posting the issue, we definitely also accept pull requests! as you apparently noticed, there indeed is no parser for Compass Group restaurants yet. feel free to write one, and don't hesitate to ask if you encounter problems of any kind!

there is some information on setting up a local development environment and writing menu parsers in READMEs across the repository, but some of it might also be outdated.

**Comment by otahontas** [comment]
Sounds good! I'll follow up with PR at some point

**Comment by maxjvh** [comment]
Luova added, thanks to PR #19
