### ISSUE TITLE
Make some changes to Arabia&Kumpula area providers

### ISSUE THREAD

**Issue by otahontas** [Kanttiinit/kitchen#23]
Hi, 

There have been some changes regarding the area's student lunch providers:
- Ravintola Arabianranta provides student lunch and the parser for food&co already works for fetching their lunch details. Here's the API address for this week: http://www.foodandco.fi/api/restaurant/menu/week?language=fi&restaurantPageId=321259&weekDate=2021-10-21
- Jamipaja has been discontinued
- Metropolia Hämeentie has been discontinued

I was looking to create PR to address these, but it looks like the API addresses are not in the repo, but rather in some internal database?

**Comment by maxjvh** [comment]
hey, thanks for the information! the data indeed resides in a Postgres database and is not a part of this repo. i've added Arabianranta and removed Jamipaja and Metropolia Hämeentie.
