### ISSUE TITLE
Cannot start the development server

### ISSUE THREAD

**Issue by thesauri** [Kanttiinit/kitchen#6]
I'm trying to get the development environment running locally to add proper vegan food parsing for Täffä. I have added a `.env` file with the following contents to the root folder:

```
DATABASE_URL=postgresql:///kanttiinit
SESSION_SECRET=randomstring
BOT_TOKEN=yetanotherrandomstring
ORIGINS=localhost
```

Once started, I repeatedly get the following error: `Failed to fetch updates. Waiting: 1s 404: Not Found`.

I have created a local PostgreSQL database with the name `kanttiinit` and PostgreSQl is running locally.

`BOT_TOKEN` was not mentioned in the `README`. However, I couldn't start the server at all without the token. Similarly, `ORIGINS` was marked as optional, but the server wouldn't start without any values.

Any advice?

**Comment by bodyflex** [comment]
@thesauri sorry about the poor documentation here; it's not up to date.

i've just pushed a commit to master that makes most environment variables optional in development mode. now you should only have to set `DATABASE_URL` in the `.env` file for a bare minimum working server. let me know if you run into further issues!
